version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - redis
    volumes:
      - .:/app
    env_file:
      - .env
  # worker:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - redis
  #   volumes:
  #     - .:/app
  #   env_file:
  #     - .env

  redis:
    image: "redis:alpine"
